services:
    xhrequester:
        class: Travels\Bundle\ServiceBundle\Classes\XHRequesterImpl
#    travels_service.example:
#        class: Travels\Bundle\ServiceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
